version: "3.5"

services:

  pushgateway:
    image: prom/pushgateway:v1.0.0
    container_name: pushgateway
    ports:
      - "9091:9091"

  simplewebserver:
    build:
      context: ..
      dockerfile: dockerfiles/simpleTestServer.Dockerfile
    depends_on:
      - pushgateway
    ports:
      - "8080:8080"

  pme_app:
    build:
      context: ..
      dockerfile: dockerfiles/pmeClient.Dockerfile
    container_name: pme_app
    depends_on:
      - simplewebserver
      - pushgateway
    entrypoint: ./test/e2e/test_runner.sh
